<a href="https://colab.research.google.com/github/revan-desai/Pandas_basic/blob/main/pandas_sorting_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df=pd.DataFrame({'p':range(4),'q':range(2,6)})

print(df)

   p  q
0  0  2
1  1  3
2  2  4
3  3  5

In [2]:
df.transform(lambda x: x + 2)    # will add 2 into each value present in the Dataframe

   p  q
0  2  4
1  3  5
2  4  6
3  5  7

In [21]:
import pandas as pd

df=pd.Series(range(25,4,-5))

print(df)

print("*************************************")

df=pd.Series(range(4))

print(df)

0    25
1    20
2    15
3    10
4     5
dtype: int64
*************************************
0    0
1    1
2    2
3    3
dtype: int64

In [23]:
import numpy as np



df=pd.Series(range(5))

df1=df.transform([np.sqrt,np.exp])

df1

       sqrt        exp
0  0.000000   1.000000
1  1.000000   2.718282
2  1.414214   7.389056
3  1.732051  20.085537
4  2.000000  54.598150