<a href="https://colab.research.google.com/github/revan-desai/Pandas_basic/blob/main/pandas_ipl_data_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd

data={'Name':['nitesh','anu','mukesh','suresh','rajiv','john','vicky'],'Gender':['M','F','M','M','M','M','M'] ,'City':['mumbai','pune','delhi','kolkata','chennai','mumbai','pune'] ,
      'Frequency':['daily','weekly','once','weekly','monthly','daily','monthly'] ,'item':['burger','sandwitch','pizza','rasgulla','idli','burger','pizza'], 'spends':[150,80,200,40,50,120,350]}

food=pd.DataFrame(data)

food

     Name Gender     City Frequency       item  spends
0  nitesh      M   mumbai     daily     burger     150
1     anu      F     pune    weekly  sandwitch      80
2  mukesh      M    delhi      once      pizza     200
3  suresh      M  kolkata    weekly   rasgulla      40
4   rajiv      M  chennai   monthly       idli      50
5    john      M   mumbai     daily     burger     120
6   vicky      M     pune   monthly      pizza     350

In [32]:
from pandas.core.apply import AggFuncType
food.pivot_table(index='City',columns=['item'],values='spends',aggfunc='sum')

item     burger  idli  pizza  rasgulla  sandwitch
City
chennai     NaN  50.0    NaN       NaN        NaN
delhi       NaN   NaN  200.0       NaN        NaN
kolkata     NaN   NaN    NaN      40.0        NaN
mumbai    270.0   NaN    NaN       NaN        NaN
pune        NaN   NaN  350.0       NaN       80.0